---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway-ui
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
    nodePort: 30808
  selector:
    app: api-gateway
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: api-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
      labels:
        app: api-gateway
    spec:
      containers:
      - image: "{{ .Values.admin.image.repositoryServer }}/{{ .Values.admin.image.repositoryProject }}/api-gateway:{{ .Values.admin.image.tag }}"
        name: api-gateway
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          initialDelaySeconds: 90
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
          initialDelaySeconds: 15
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        ports:
        - containerPort: 8080
      restartPolicy: Always
