{{ if .Values.httpproxy.enabled }}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: spring-petclinic-api
  name: spring-petclinic-api-proxy
  namespace: {{ .Release.Namespace }}
spec:
  routes:
  - conditions:
    - prefix: /
    pathRewritePolicy:
      replacePrefix:
      - prefix: /
        replacement: /
    services:
    - name: api-gateway
      port: 8080
  virtualhost:
    fqdn: petclinic.{{ .Values.dns.subdomain }}.{{ .Values.dns.domain }}
{{ end}}
