{
 "title": "PetClinic",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(jvm_memory_used_bytes, app)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes{app=\"$application\"}, instance)"
   },
   {
    "name": "uri",
    "label": "URI",
    "query": "label_values(http_server_requests_seconds_count{app=\"$application\", instance=~\"$instance\"}, uri)"
   }
  ]
 },
 "panels": [
  {
   "title": "Accumulative JVM memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{kubernetes_namespace=\"spring-petclinic\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Top 10 Slowest API Endpoints",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_max{app=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[5m])))"
    }
   ]
  },
  {
   "title": "Top 10 Most Used API Endpoints",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_count{app=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[5m])))"
    }
   ]
  }
 ]
}